sudo: false

language: php
php:
  - 8.1
  - 8.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - composer validate
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/
